name: les_twiix_app
description: Application communautaire officielle Les Twiix
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0
  flame: ^1.32.0
  audioplayers: 6.4.0

  url_launcher: ^6.3.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_source.jpg
    - assets/images/twiix_profile_logo.png
    - assets/images/twiix_offline_pixel.png
    - assets/images/twiix_live_pixel.png
    - assets/images/social_instagram.png
    - assets/images/social_tiktok.png
    - assets/images/mascotte_run_frame.png
    - assets/images/mascotte_run_cover.png
    - assets/images/mascotte_run_grenoble.png
    - assets/images/mascotte_run_marseille.png
    - assets/images/mascotte_run_paris.png
    - assets/images/mascotte_run_marseille_vieux_port.png
    - assets/images/mascotte_run_marseille_velodrome.png
    - assets/images/mascotte_run_marseille_calanques.png
    - assets/images/mascotte_run_grenoble_bastille.png
    - assets/images/mascotte_run_grenoble_quais.png
    - assets/images/mascotte_run_grenoble_bulles.png
    - assets/images/mascotte_run_paris_eiffel.png
    - assets/images/mascotte_run_paris_notre_dame.png
    - assets/images/mascotte_run_paris_parc_des_princes.png
    - assets/images/mascotte_run_wendy.png
    - assets/images/mascotte_run_swan.png
    - assets/images/mascotte_run_dean.png
    - assets/images/mascotte_run_twiix.png
    - assets/images/planning_source.jpeg
    - assets/images/badges/
    - assets/images/badges/mascotte_run/
    - assets/audio/mascotte_run_music.ogg
    - assets/audio/mascotte_jump.wav
    - assets/audio/mascotte_ball.wav
    - assets/audio/mascotte_collision.wav
    - assets/audio/mascotte_record.wav
