name: les_twiix_app
description: Application communautaire officielle Les Twiix
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_source.jpg
    - assets/images/planning_source.jpeg
