name: les_twiix_app
description: Application communautaire officielle Les Twiix
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_source.jpg
    - assets/images/twiix_profile_logo.png
    - assets/images/twiix_offline_pixel.png
    - assets/images/twiix_live_pixel.png
    - assets/images/planning_source.jpeg
    - assets/images/badges/
